// <auto-generated />
using System;
using Billing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Billing.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Billing.Models.BillingRun", b =>
                {
                    b.Property<int>("BillingRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillingRunID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BillingRunId"));

                    b.Property<int?>("DurationMilliseconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("InvoicesGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("InvoicesMarkedOverdue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RunType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TrialActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("BillingRunId")
                        .HasName("PRIMARY");

                    b.ToTable("billing_runs", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeatureID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("FeatureId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FeatureKey" }, "FeatureKey")
                        .IsUnique();

                    b.ToTable("features", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateOnly>("BillingPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BillingPeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("CoachCount")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Pending','Paid','Cancelled','Overdue')")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int>("OrganizationSubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationSubscriptionID");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<decimal>("PricePerCoach")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PlanId" }, "FK_Invoices_Plans");

                    b.HasIndex(new[] { "PromotionId" }, "FK_Invoices_Promotions");

                    b.HasIndex(new[] { "OrganizationId" }, "IDX_Invoices_OrganizationID");

                    b.HasIndex(new[] { "OrganizationSubscriptionId" }, "IDX_Invoices_OrganizationSubscriptionID");

                    b.HasIndex(new[] { "OrganizationSubscriptionId", "BillingPeriodStart", "BillingPeriodEnd" }, "UX_Invoice_Subscription_BillingPeriod")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrganizationId"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CurrentPlanId")
                        .HasColumnType("int")
                        .HasColumnName("CurrentPlanID");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("OrganizationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CurrentPlanId" }, "FK_Organizations_Plans");

                    b.HasIndex(new[] { "IsActive" }, "IDX_Organizations_IsActive");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Billing.Models.OrganizationSubscription", b =>
                {
                    b.Property<int>("OrganizationSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizationSubscriptionID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrganizationSubscriptionId"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte>("AutoRenew")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<sbyte>("IsTrial")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("LastBilledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MinimumMonthlyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MonthlyPricePerCoach")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<string>("OrganizationSubscriptionscol")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("organization_subscriptionscol");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Active','Cancelled','Expired')")
                        .HasDefaultValueSql("'Active'");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TrialStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("OrganizationSubscriptionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrganizationId" }, "IDX_OrgSub_OrganizationID");

                    b.HasIndex(new[] { "PlanId" }, "IDX_OrgSub_PlanID");

                    b.HasIndex(new[] { "Status" }, "IDX_OrgSub_Status");

                    b.ToTable("organization_subscriptions", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("'CAD'");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("enum('Pending','Succeeded','Failed','Refunded')");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ProviderTransactionID");

                    b.HasKey("PaymentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "InvoiceId" }, "IDX_Payments_InvoiceID");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Planfeature", b =>
                {
                    b.Property<int>("PlanFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanFeatureID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanFeatureId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnName("FeatureID");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.HasKey("PlanFeatureId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FeatureId" }, "FK_PlanFeatures_Features");

                    b.HasIndex(new[] { "PlanId", "FeatureId" }, "UK_Plan_Feature")
                        .IsUnique();

                    b.ToTable("planfeatures", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("enum('Percentage','FixedAmount','PriceOverride')");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PromotionId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PlanId" }, "FK_Promotions_Plans");

                    b.HasIndex(new[] { "IsActive" }, "IDX_Promotions_IsActive");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("Billing.Models.SubscriptionEvent", b =>
                {
                    b.Property<int>("SubscriptionEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionEventID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubscriptionEventId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("EffectiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("enum('Created','Activated','PlanChanged','Cancelled','Expired','Suspended','Reactivated')");

                    b.Property<int?>("NewPlanId")
                        .HasColumnType("int")
                        .HasColumnName("NewPlanID");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OldPlanId")
                        .HasColumnType("int")
                        .HasColumnName("OldPlanID");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<int?>("OrganizationSubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationSubscriptionID");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("SubscriptionEventId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NewPlanId" }, "FK_SubEvents_NewPlan");

                    b.HasIndex(new[] { "OldPlanId" }, "FK_SubEvents_OldPlan");

                    b.HasIndex(new[] { "EffectiveAt" }, "IDX_SubEvents_EffectiveAt");

                    b.HasIndex(new[] { "EventType" }, "IDX_SubEvents_EventType");

                    b.HasIndex(new[] { "OrganizationId" }, "IDX_SubEvents_OrganizationID");

                    b.HasIndex(new[] { "OrganizationSubscriptionId" }, "IDX_SubEvents_SubscriptionID");

                    b.ToTable("subscription_events", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Subscriptionplan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal>("MinimumMonthlyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PricePerCoach")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PlanId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IsActive" }, "IDX_SubscriptionPlans_IsActive");

                    b.HasIndex(new[] { "PlanName" }, "PlanName")
                        .IsUnique();

                    b.ToTable("subscriptionplans", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Tenantregistry", b =>
                {
                    b.Property<int>("TenantRegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TenantRegistryID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TenantRegistryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("longtext");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizationID");

                    b.Property<string>("Subdomain")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("TenantRegistryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrganizationId" }, "IDX_TenantRegistry_OrganizationID");

                    b.ToTable("tenantregistry", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Billing.Models.Invoice", b =>
                {
                    b.HasOne("Billing.Models.Organization", "Organization")
                        .WithMany("Invoices")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Organizations");

                    b.HasOne("Billing.Models.OrganizationSubscription", "OrganizationSubscription")
                        .WithMany("Invoices")
                        .HasForeignKey("OrganizationSubscriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_OrganizationSubscriptions");

                    b.HasOne("Billing.Models.Subscriptionplan", "Plan")
                        .WithMany("Invoices")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Plans");

                    b.HasOne("Billing.Models.Promotion", "Promotion")
                        .WithMany("Invoices")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_Invoices_Promotions");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationSubscription");

                    b.Navigation("Plan");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Billing.Models.Organization", b =>
                {
                    b.HasOne("Billing.Models.Subscriptionplan", "CurrentPlan")
                        .WithMany("Organizations")
                        .HasForeignKey("CurrentPlanId")
                        .HasConstraintName("FK_Organizations_Plans");

                    b.Navigation("CurrentPlan");
                });

            modelBuilder.Entity("Billing.Models.OrganizationSubscription", b =>
                {
                    b.HasOne("Billing.Models.Organization", "Organization")
                        .WithMany("OrganizationSubscriptions")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrgSub_Organizations");

                    b.HasOne("Billing.Models.Subscriptionplan", "Plan")
                        .WithMany("OrganizationSubscriptions")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_OrgSub_Plans");

                    b.Navigation("Organization");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Billing.Models.Payment", b =>
                {
                    b.HasOne("Billing.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Invoices");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Billing.Models.Planfeature", b =>
                {
                    b.HasOne("Billing.Models.Feature", "Feature")
                        .WithMany("Planfeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanFeatures_Features");

                    b.HasOne("Billing.Models.Subscriptionplan", "Plan")
                        .WithMany("Planfeatures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanFeatures_Plans");

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Billing.Models.Promotion", b =>
                {
                    b.HasOne("Billing.Models.Subscriptionplan", "Plan")
                        .WithMany("Promotions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Promotions_Plans");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Billing.Models.SubscriptionEvent", b =>
                {
                    b.HasOne("Billing.Models.Subscriptionplan", "NewPlan")
                        .WithMany("SubscriptionEventNewPlans")
                        .HasForeignKey("NewPlanId")
                        .HasConstraintName("FK_SubEvents_NewPlan");

                    b.HasOne("Billing.Models.Subscriptionplan", "OldPlan")
                        .WithMany("SubscriptionEventOldPlans")
                        .HasForeignKey("OldPlanId")
                        .HasConstraintName("FK_SubEvents_OldPlan");

                    b.HasOne("Billing.Models.Organization", "Organization")
                        .WithMany("SubscriptionEvents")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubEvents_Organizations");

                    b.HasOne("Billing.Models.OrganizationSubscription", "OrganizationSubscription")
                        .WithMany("SubscriptionEvents")
                        .HasForeignKey("OrganizationSubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SubEvents_Subscriptions");

                    b.Navigation("NewPlan");

                    b.Navigation("OldPlan");

                    b.Navigation("Organization");

                    b.Navigation("OrganizationSubscription");
                });

            modelBuilder.Entity("Billing.Models.Tenantregistry", b =>
                {
                    b.HasOne("Billing.Models.Organization", "Organization")
                        .WithMany("Tenantregistries")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TenantRegistry_Organizations");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Models.Feature", b =>
                {
                    b.Navigation("Planfeatures");
                });

            modelBuilder.Entity("Billing.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Billing.Models.Organization", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrganizationSubscriptions");

                    b.Navigation("SubscriptionEvents");

                    b.Navigation("Tenantregistries");
                });

            modelBuilder.Entity("Billing.Models.OrganizationSubscription", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("SubscriptionEvents");
                });

            modelBuilder.Entity("Billing.Models.Promotion", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Billing.Models.Subscriptionplan", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrganizationSubscriptions");

                    b.Navigation("Organizations");

                    b.Navigation("Planfeatures");

                    b.Navigation("Promotions");

                    b.Navigation("SubscriptionEventNewPlans");

                    b.Navigation("SubscriptionEventOldPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
