// <auto-generated />
using System;
using ClassLift.Diagnostic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLift.Diagnostic.Data.Migrations
{
    [DbContext(typeof(DiagnosticDbContext))]
    [Migration("20260824230820_AddTopPriorities")]
    partial class AddTopPriorities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClassLift.Diagnostic.Models.DiagnosticLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdditionalNeeds")
                        .HasColumnType("longtext");

                    b.Property<int>("AdminCount")
                        .HasColumnType("int");

                    b.Property<string>("AiSummary")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BuyingCriteriaJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CostOfInactionJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentToolsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("DesiredOutcome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<int>("FinancialControlScore")
                        .HasColumnType("int");

                    b.Property<string>("ImplementationTimeline")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImprovementAreasJson")
                        .HasColumnType("json");

                    b.Property<int>("KeyPersonDependency")
                        .HasColumnType("int");

                    b.Property<int>("KeyPersonScore")
                        .HasColumnType("int");

                    b.Property<string>("LeadIntent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("OperationalEfficiencyScore")
                        .HasColumnType("int");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PreviousSolutionsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("PrimaryPain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RecommendedModulesJson")
                        .HasColumnType("json");

                    b.Property<string>("RootCause")
                        .HasColumnType("longtext");

                    b.Property<int>("ScalabilityScore")
                        .HasColumnType("int");

                    b.Property<string>("SelfIdentifiedPriority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentCount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SystemizationScore")
                        .HasColumnType("int");

                    b.Property<string>("TopPrioritiesJson")
                        .HasColumnType("json");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("LeadIntent");

                    b.ToTable("diagnostic_leads", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
